name: Pull Request
on: [pull_request]
jobs:
  test:
    name: Test changes
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: "altmp/altv-types"
      - name: Install dependencies
        run: yarn install
      - name: Test
        run: yarn run test
      - name: Lint
        run: yarn run lint
